<a href="https://colab.research.google.com/github/Tejav202/IETE/blob/main/week2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import math
import math as m
from math import sqrt,pow

In [2]:
import math
print("square root  of 10 ",math.sqrt(10))

square root  of 10  3.1622776601683795


In [3]:
print("exponential of 2",math.exp(2))

exponential of 2 7.38905609893065


In [4]:
print("natural log of 10",math.log(10))
print(" log base 10 of 1000",math.log(1000,10))

natural log of 10 2.302585092994046
 log base 10 of 1000 2.9999999999999996


In [8]:
print("sine 90 degrees",math.sin(math.radians(90)))
print("cosine 0 degrees",math.cos(math.radians(0)))
print("tangent 45 degrees",math.tan(math.radians(45)))


sine 90 degrees 1.0
cosine 0 degrees 1.0
tangent 45 degrees 0.9999999999999999


In [10]:
print("value of pi",math.pi)
print("value of e",math.e)
print("positive infinity",math.inf)
print("not a number(nan)",math.nan)


value of pi 3.141592653589793
value of e 2.718281828459045
positive infinity inf
not a number(nan) nan


In [11]:
radius=5
area=math.pi*radius*radius
print(area)

78.53981633974483


In [13]:
radius=7
area=math.pi*radius**2
circumference=2*math.pi*radius
print(area)
print(circumference)


153.93804002589985
43.982297150257104


In [20]:
degree=90
radian=math.radians(degree)
print("degree to radians",math.radians(degree))
print("radians to degree",math.degrees(radian))

degree to radians 1.5707963267948966
radians to degree 90.0


In [21]:
a=5
b=6
a=b
print("a:",a)
print("b:",b)

a: 6
b: 6


In [22]:
a=5
b=6
temp=a
a=b
b=temp
print("a:",a)
print("b:",b)

a: 6
b: 5


In [23]:
a=5
b=6
a=a+b
b=a-b
a=a-b
print("a:",a)
print("b:",b)


a: 6
b: 5


In [24]:
a=5
b=6
a=a^b
b=a^b
a=a^b
print("a:",a)
print("b:",b)

a: 6
b: 5


In [25]:
a=5
b=6
a,b=b,a
print("a:",a)
print("b:",b)

a: 6
b: 5


In [26]:
a=10
b=20
temp=a
a=b
b=temp
print("a:",a)
print("b:",b)

a: 20
b: 10


In [27]:
a=30
b=40
a=a+b
b=a-b
a=a-b
print("a:",a)
print("b:",b)

a: 40
b: 30


In [28]:
a=7
b=9
a=a^b
b=a^b
a=a^b
print("a:",a)
print("b:",b)

a: 9
b: 7


In [29]:
a=100
b=200
a,b=b,a
print("a:",a)
print("b:",b)

a: 200
b: 100


In [30]:
if True:
  print("this will give an error")

this will give an error


In [32]:
marks=45
if marks>=50:
  print("you passed exam")
else:
    print("you failed exam")

you failed exam


In [33]:
num=15
if num>0:
  print("positive number")
  if num%5==0:
    print("divisible by 5")

positive number
divisible by 5


In [36]:
temp=30
if temp>35:
  print("its very hot")
elif temp>25:
  print("its warm")
elif temp>15:
    print("its cool")
else:
    print("its very cold")


its warm


In [37]:
count=1
while count<=5:
  print("count is",count)
  count+=1

count is 1
count is 2
count is 3
count is 4
count is 5


In [41]:
count=1
while count<=5:
  print(count,end=" ")
  count+=1

1 2 3 4 5 

In [43]:
i=1
while i<=5:
  j=1
  while j<=i:
    print("*",end ="")
    j+=1
  print()
  i+=1

*
**
***
****
*****


In [44]:
n=1
total=0
while n<=10:
  total+=n
  n+=1
print("sum is",total)

sum is 55


In [53]:
for i in range(1,6):
  if i==3:
    continue
  print(i)

1
2
4
5


In [54]:
for i in range(1,6):
  if i==3:
    break
  print(i)

1
2


In [56]:
for i in range(1,6):
  if i==3:
    pass
  else:
    print(i)

1
2
4
5


In [62]:
for i in range(1,10):
  if i==6:
    break
  print(i)

1
2
3
4
5


In [69]:
for i in range(1,10):
  if i==4:
    continue
  print(i)

1
2
3
5
6
7
8
9


In [72]:
for i in range(1,10):
  if i==8:
    pass
  else:
    print(i)

1
2
3
4
5
6
7
9


In [74]:
print("#",end=" ")
print("#",end=" ")
print("#",end=" ")

# # # 

In [75]:
print("#")
print("#")
print("#")

#
#
#


In [77]:
for i in range(5):
  print("#",end= " ")

# # # # # 

In [82]:
for row in range(4):
    for col in range(4):
        print("#", end=" ")
    print()  # Moves to the next line after each row


# # # # 
# # # # 
# # # # 
# # # # 


In [85]:
import array as arr

In [86]:
numbers=arr.array('i',[10,20,30,40,50])

In [88]:
print(numbers.buffer_info())

(138731647134064, 5)


In [89]:
print(numbers.typecode)

i


In [90]:
numbers.append(60)
print(numbers)

array('i', [10, 20, 30, 40, 50, 60])


In [91]:
for num in numbers:
  print(num)

10
20
30
40
50
60


In [93]:
import numpy as np


In [95]:
from numpy import *
mat=array([[1,2,3],[4,5,6],[7,8,9]])
print(mat)
print(mat[0])
print("element at(2,3)",mat[1][2])
print("all rows of 2nd column",mat[:,1])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[1 2 3]
element at(2,3) 6
all rows of 2nd column [2 5 8]
